--- @meta

LibGroupBroadcast = {}

BOSS_BAR = {}
CENTER_SCREEN_ANNOUNCE = {}
COMPASS = {}
ENDLESS_DUNGEON_MANAGER = {}
SHARED_INVENTORY = {}

ACTION_RESULT_DIED = 2260
ACTION_RESULT_DIED_XP = 2262
ENDLESS_DUNGEON_GROUP_TYPE_SOLO = 0
HOTBAR_CATEGORY_PRIMARY = 0
HOTBAR_CATEGORY_TEMPORARY = 9
LIBINFINITEARCHIVE_AUDITOR_NAME = 0
LIBINFINITEARCHIVE_TOMESHELL = 0
MAP_PIN_TYPE_QUEST_INTERACT = 8
MAX_PET_UNIT_TAGS = 7
