--- @meta

LibInifiniteArchive = {}
LibGroupBroadcast = {}

BOSS_BAR = {}
CENTER_SCREEN_ANNOUNCE = {}
COMPASS = {}
ENDLESS_DUNGEON_MANAGER = {}
SHARED_INVENTORY = {}

ACTION_RESULT_DIED = 2260
ACTION_RESULT_DIED_XP = 2262
ENDLESS_DUNGEON_GROUP_TYPE_SOLO = 0
HOTBAR_CATEGORY_PRIMARY = 0
HOTBAR_CATEGORY_TEMPORARY = 9
LIBINFINITEARCHIVE_AUDITOR_NAME = 0
LIBINFINITEARCHIVE_CROSSING_FAIL = 0
LIBINFINITEARCHIVE_CROSSING_SUCCESS = 0
LIBINFINITEARCHIVE_FILERS_WING_FAIL = 0
LIBINFINITEARCHIVE_FILERS_WING_SUCCESS = 0
LIBINFINITEARCHIVE_HAEFAL_FAIL = 0
LIBINFINITEARCHIVE_HAEFAL_START = 0
LIBINFINITEARCHIVE_HAEFAL_SUCCESS = 0
LIBINFINITEARCHIVE_GW = 0
LIBINFINITEARCHIVE_HERD = 0
LIBINFINITEARCHIVE_HERD_FAIL = 0
LIBINFINITEARCHIVE_HERD_SUCCESS = 0
LIBINFINITEARCHIVE_THEATRE_FAIL = 0
LIBINFINITEARCHIVE_THEATRE_SUCCESS = 0
LIBINFINITEARCHIVE_TOMESHELL = 0
MAP_PIN_TYPE_QUEST_INTERACT = 8
MAX_PET_UNIT_TAGS = 7
POWERTYPE_ULTIMATE = 10

SI_ENDLESSDUNGEONBUFFTYPE_AVATAR2 = 4651
SI_ENDLESSDUNGEONBUFFBUCKETTYPE0 = 4652
SI_ENDLESSDUNGEONBUFFBUCKETTYPE1 = 4653
SI_ENDLESSDUNGEONBUFFBUCKETTYPE2 = 4654

--- @return table
function ZO_ShallowNumericallyIndexedTableCopy(source, dest) end
