--- @meta

-- LibGroupBroadcast = {}

LIBINFINITEARCHIVE_MAP_DESTOZUNOS_LIBRARY = 0
LIBINFINITEARCHIVE_MAP_ECHOING_DEN = 0
LIBINFINITEARCHIVE_MAP_FILERS_WING = 0
LIBINFINITEARCHIVE_MAP_HAEFALS_BUTCHERY = 0
LIBINFINITEARCHIVE_MAP_THEATRE_OF_WAR = 0
LIBINFINITEARCHIVE_MAP_TREACHEROUS_CROSSING = 0
LIBINFINITEARCHIVE_MARAUDER_BITTOG = 0
LIBINFINITEARCHIVE_MARAUDER_GOTHMAU = 0
LIBINFINITEARCHIVE_MARAUDER_HILKARAX = 0
LIBINFINITEARCHIVE_MARAUDER_ULMOR = 0
LIBINFINITEARCHIVE_MARAUDER_ZULFIMBUL = 0
LIBINFINITEARCHIVE_AUDITOR_NAME = 0
LIBINFINITEARCHIVE_CROSSING_SUCCESS = 0
LIBINFINITEARCHIVE_CROSSING_FAIL = 0
LIBINFINITEARCHIVE_FILERS_WING_FAIL = 0
LIBINFINITEARCHIVE_FILERS_WING_SUCCESS = 0
LIBINFINITEARCHIVE_GW = 0
LIBINFINITEARCHIVE_HAEFAL_START = 0
LIBINFINITEARCHIVE_HAEFAL_SUCCESS = 0
LIBINFINITEARCHIVE_HAEFAL_FAIL = 0
LIBINFINITEARCHIVE_HERD = 0
LIBINFINITEARCHIVE_HERD_FAIL = 0
LIBINFINITEARCHIVE_HERD_SUCCESS = 0
LIBINFINITEARCHIVE_THEATRE_FAIL = 0
LIBINFINITEARCHIVE_THEATRE_SUCCESS = 0
LIBINFINITEARCHIVE_TOMESHELL = 0
